import { CustomError } from "@/core/errors";
import { apiError } from "@/core/api-responses/api-error";
import { getListSessionService } from "../services/get-list-session.service";
import { Role } from "@/core/enums/role.enum";
import { authenticate } from "@/core/lib/auth";
import { apiSuccess } from "@/core/api-responses/api-success";

export async function GetListSessionController(
  request: Request,
  { params }: { params: { listId: string } },
) {
  try {
    const userId = await authenticate(request, Role.USER);
    const response = await getListSessionService(params.listId, userId);
    return apiSuccess(response);
  } catch (error) {
    if (error instanceof CustomError) {
      return apiError(error);
    }
    return apiError(
      new CustomError({
        message:
          "Se ha producido un error inesperado al obtener la sesi√≥n de la lista",
      }),
    );
  }
}
